---
# file: group_vars/all

username: iwiebe
full_name: Isaac Wiebe
shell: /usr/bin/zsh
user_password: vault_iwiebe_password
# define the key_name if you want to send your workstation key to server user
#key_name: id_rsa

github_user: iwiebe

ansible_user: root

# system/default vars
hostname: "{{ inventory_hostname }}"
client_ip: "{{ ansible_host }}/23"
storage_ip: "{{ storage_host }}/24"

## define network
client_gw: "192.168.0.1"
client_dns4: "192.168.0.2"

## team vars
nmcli_team:
  - conn_name: client-side
    ip4: "{{ client_ip }}"
    gw4: "{{ client_gw }}"
    dns4: "{{ client_dns4 }}"
    mtu: 9000
  - conn_name: storage-side
    ip4: "{{ storage_ip }}"
    gw4: "0.0.0.0"
    dns4: "127.0.0.1"
    mtu: 9000

## ethernet vars
nmcli_ethernet:
  - conn_name: "client-side-{{ client_ifname }}"
    ifname: "{{ client_ifname }}"
    ip4: "{{ client_ip }}"
    gw4: "{{ client_gw }}"
    dns4: "{{ client_dns4 }}"
