---
# file: group_vars/ceph_osds_ssd.yml

## system vars
storage_host: "192.168.50.{{ ansible_host | regex_replace('192.168.0.') }}"

## add ethernet interface
eth_type: "team"

## add team interface
nmcli_team_slave:
  - conn_name: client-slave-enp1s0f0
    ifname: enp1s0f0
    master: client-side
  - conn_name: storage-slave-enp2s0f0
    ifname: enp2s0f0
    master: storage-side

## permitted interface(s), must be defined to clean up remaining interfaces
permitted_interfaces:
  - "client-side"
  - "storage-side"
  - "lo"
