---
# file: roles/cephadm/tasks/main.yml

- name: install podman pre-requisite
  dnf:
    name: podman
    state: latest
  become: yes
  
- name: fetch cephadm script
  get_url:
    url: https://github.com/ceph/ceph/raw/octopus/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0770'

- name: Create ceph directory if it does not exist
  file:
    path: /etc/ceph
    state: directory
    mode: '0755'

- name: add ceph repo
  command: "/root/cephadm add-repo --release octopus"

- name: install cephadm
  dnf:
    name: cephadm
    state: installed
  become: yes

- name: send osd spec
  copy: 
    src: "{{ item }}"
    dest: "/etc/ceph/{{ item }}" 
    mode: '0755'
  with_items:
    - osd_spec.yml

