---
# file: host_vars/_tempalate.yml
# vars in this file will override group_vars/all.yml

## system vars
hostname: "override hostname here"

## add ethernet interface
eth_type: "eth"
client_ip: "192.168.0.x/23"
client_dns4: "192.168.0.2"
client_ifname: "ens18"

## remove default interface(s)
del_interfaces:
  - conn_name: "ens18"
  - conn_name: "ens19"