---
# file: roles/ansible-control/tasks/main.yml

- name: Copy master ssh keys
  copy: 
    src: "{{ item }}"
    dest: "/root/.ssh/{{ item }}" 
    mode: 0600
  with_items:
    - id_rsa
    - id_rsa.pub
  tags: ssh

- name: Installing EPEL
  yum:
    name: epel-release
    state: present
  tags: epel

- name: Installing git
  yum:
    name: git
    state: present
  tags: git

- name: Installing python 3.6
  yum:
    name: python36
    state: present
  tags: python

- name: Installing pip3
  yum:
    name: python36-pip
    state: present
  tags: python

- name: Upgrading pip3
  command: pip3 install --upgrade pip

- name: Installing ansible library via pip
  pip:
    name: ansible
    executable: pip3

- name: Clone village-ansible repository
  git:
    repo: 'https://github.com/villagechurch/village-ansible.git'
    dest: /srv/village-ansible
