---
# file: roles/common/tasks/main.yml

- name: be sure packages are installed
  package:
    name: 
      - chrony
      - bind-utils
    state: present

- name: be sure chronyd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes

- name: ensure timezone is UTC
  timezone:
    name: UTC

- name: set hostname
  hostname:
    name: "{{ hostname }}"

- name: add FQDN line to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1   {{ hostname }}.thisisvillage.church {{ hostname }}"
    state: present
