---
# file: roles/common/tasks/main.yml

- name: be sure chrony is installed
  package:
    name: chrony
    state: present
  become: yes
  tags: first-run

- name: be sure chronyd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes

- name: ensure timezone is UTC
  timezone:
    name: UTC
