---
# file: roles/common/tasks/main.yml

- name: install essentials
  dnf:
    name:
      - epel-release
    update_cache: true

- name: ensure the EPEL key is in place
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-8

- name: be sure python3 is installed
  dnf:
    name: python3
    state: present
  become: yes
  tags: python3
  
- name: be sure chrony is installed
  dnf:
    name: chrony
    state: present
  become: yes
  tags: chrony

- name: be sure chronyd is running and enabled
  service:
    name: chronyd
    state: started
    enabled: yes
  tags: chrony

- name: ensure timezone is UTC
  timezone:
    name: UTC
