---
# file: roles/samba-vfsceph/tasks/main.yml

- name: Installing samba
  package:
    name:
      - samba
    state: present

- name: be sure samba is running and enabled
  service:
    name: smb
    state: started
    enabled: yes

- name: copy samba config
  copy: 
    src: "{{ item }}"
    dest: "/etc/samba/{{ item }}" 
    mode: 0644
  with_items:
    - smb.conf
  notify:
    - restart samba

- name: permit traffic in default zone for samba service
  ansible.posix.firewalld:
    service: samba
    permanent: yes
    state: enabled
  notify:
    - restart firewalld

- name: copy avahi service config
  copy: 
    src: "smb.service.avahi"
    dest: "/etc/avahi/services/smb.service" 
    mode: 0644
  notify:
    - restart avahi-daemon

## avahi service traffic permitted through firewall as a part of bootstrap

- name: ensure ceph-fuse mount is persistent
  lineinfile:
    path: /etc/fstab
    regexp: '^none    \/mnt\/mycephfs  fuse\.ceph ceph\.id=samba0,ceph\.conf=\/etc\/ceph\/ceph\.conf,_netdev,defaults  0 0'
    line: 'none    /mnt/mycephfs  fuse.ceph ceph.id=samba0,ceph.conf=/etc/ceph/ceph.conf,_netdev,defaults  0 0'


#- name: Put SELinux in permissive mode, logging actions that would be blocked.
#  ansible.posix.selinux:
#    policy: targeted
#    state: permissive

- name: Disable SELinux
  ansible.posix.selinux:
    state: disabled
