---
# file: roles/mlnx_mft/tasks/main.yml

- name: install mlnx_mft pre-requisites
  dnf:
   name:
     - gcc
     - rpm-build
     - kernel-devel
     - make
     - elfutils-libelf-devel
   state: latest
  become: yes
  
- name: fetch and unarchive MFT-4.14
  unarchive:
    src: https://www.mellanox.com/downloads/MFT/mft-4.14.0-105-x86_64-rpm.tgz
    dest: /root
    remote_src: yes

- name: run mft installer
  command: "/root/mft-4.14.0-105-x86_64-rpm/install.sh"
  become: yes
