---
# file: roles/mysql/tasks/main.yml

- name: install mysql via dnf
  dnf:
   name:
     - "@mysql"
   state: installed
  become: yes
  tags: first-run

- name: Copy mysql config
  copy: 
    src: "{{ item }}"
    dest: "/root/{{ item }}"
    mode: 0600
  with_items:
    - .my.cnf
#  notify: restart influxdb

- name: be sure mysqld is running and enabled
  service:
    name: mysqld
    state: started
    enabled: yes

# required to use the Ansible mysql modules
- name: install PyMySQL via pip
  pip:
    name: PyMySQL
  tags: first-run

# 'localhost' needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: update mysql root password and add all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ root_db_password }}"
    priv: '*.*:ALL,GRANT'
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true
  
- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ inventory_hostname }}"
  tags: first-run

- name: remove the test database
  mysql_db: name=test state=absent
  tags: first-run

- name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
  mysql_user:
    name: "{{ username }}"
    host: "{{ item }}"
    password: "{{ user_password }}"
    priv: '*.*:ALL,GRANT'
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
  no_log: true
