---
# file: roles/cephadm/tasks/main.yml

- name: check for pre-requisites
  package:
    name:
      - systemd
      - podman
      - chrony
      - lvm2
      - python3
    state: present
  become: yes
  
- name: fetch cephadm script
  get_url:
    url: https://raw.githubusercontent.com/ceph/ceph/octopus/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0770'
  notify:
    - create ceph directory
    - add ceph repo
    - install cephadm
    - install ceph-common

- name: Copy ssh config
  copy: 
    src: "ssh_config"
    dest: "/root/.ssh/config" 
    mode: 0600
#  notify:
#    - update ceph ssh config

- name: Copy host service spec
  copy: 
    src: "host_spec.yml"
    dest: "/root/host_spec.yml" 
    mode: 0755
