---
# file: roles/cephadm/tasks/main.yml

- name: check for pre-requisites
  package:
    name:
      - systemd
      - podman
      - chrony
      - lvm2
      - python3
    state: present
  become: yes
  tags: first_run
  
- name: fetch cephadm script
  get_url:
    url: https://raw.githubusercontent.com/ceph/ceph/octopus/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0770'
  notify:
    - create ceph directory
    - add ceph repo
    - install cephadm
    - install ceph-common
  tags: first_run

- name: Copy host service spec
  copy: 
    src: "specs"
    dest: "/root/" 
    mode: 0655
    directory_mode:

- name: check for ceph keyring - proof of cluster bootstrap
  stat:
    path: /etc/ceph/ceph.client.admin.keyring
  register: keyring_result
  tags: first_run

- name: Copy ssh config
  copy: 
    src: "ssh_config"
    dest: "/root/.ssh/config" 
    mode: 0600
  notify:
    - update ceph ssh config

- name: copy ssh private key to root
  shell: "ceph config-key get mgr/cephadm/ssh_identity_key > /root/.ssh/ceph.key"
  when: keyring_result.stat.exists
  tags: first_run

- name: check ssh private key permissions
  file:
    path: /root/.ssh/ceph.key
    owner: root
    group: root
    mode: '0600'
  tags: first_run
