# https://docs.ceph.com/en/latest/cephadm/drivegroups/#drivegroups
service_type: osd
service_id: default_drive_layout
placement:
  host_pattern: 'osd*'
data_devices:
  rotational: 1
db_devices:
  rotational: 0
