---
# file: roles/dns/tasks/main.yml

- name: Install CentOS 8 network manager libs
  package:
    name:
      - NetworkManager-libnm
      - nm-connection-editor
      - python3-libsemanage
      - python3-policycoreutils
    state: present
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "8"

- name: Install CentOS 7 network manager libs
  package:
    name:
      - NetworkManager-glib
      - nm-connection-editor
      - libsemanage-python
      - policycoreutils-python
    state: present
  when: ansible_facts['distribution'] == "CentOS" and ansible_facts['distribution_major_version'] == "7"

- name: Try nmcli add team - conn_name only & ip4 gw4
  community.general.nmcli:
    type: team
    conn_name: "{{ item.conn_name }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    dns4: "{{ item.dns4 }}"
    mtu: "{{ item.mtu }}"
    state: present
  with_items:
    - "{{ nmcli_team }}"
  when: eth_type == "team"
  register: team_present

- name: Try nmcli add teams-slave
  community.general.nmcli:
    type: team-slave
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    master: "{{ item.master }}"
    state: present
  with_items:
    - "{{ nmcli_team_slave }}"
  when: team_present is succeeded and eth_type == "team"
  notify:
    - restart CentOS 8 network
    - restart CentOS 7 network

## ADD a Team clean up task similar to nmcli del interfaces

- name: Try nmcli add Ethernet - conn_name only & ip4 gw4
  community.general.nmcli:
    type: ethernet
    conn_name: "{{ item.conn_name }}"
    ifname: "{{ item.ifname }}"
    ip4: "{{ item.ip4 }}"
    gw4: "{{ item.gw4 }}"
    dns4: "{{ item.dns4 }}"
    state: present
  with_items:
    - "{{ nmcli_ethernet }}"
  when: eth_type == "eth"
  notify:
    - restart CentOS 8 network
    - restart CentOS 7 network

- name: Try nmcli del interfaces - multiple
  community.general.nmcli:
    conn_name: "{{ item }}"
    state: absent
  with_items:
    - "{{ ansible_interfaces }}"
  when: permitted_interfaces is defined and item not in permitted_interfaces
  notify:
    - restart CentOS 8 network
    - restart CentOS 7 network
