---
# file: roles/ceph-host/tasks/main.yml

- name: check for pre-requisites
  package:
    name:
      - systemd
      - podman
      - chrony
      - lvm2
      - python3
    state: present
  become: yes
