---
# file: roles/ceph-host/tasks/main.yml

- name: install podman pre-requisite
  dnf:
    name: podman
    state: latest
  become: yes

- name: install iperf
  dnf:
    name: iperf3
    state: latest
  become: yes
