---
# file: roles/dns/tasks/main.yml

- name: be sure dnsmasq requirements are installed
  package:
    name:
      - dnsmasq
      - bind-utils
  tags: first_run

- name: be sure dnsmasq is running and enabled
  service:
    name: dnsmasq
    state: started
    enabled: yes
  tags: first_run

- name: copy dnsmasq config
  copy: 
    src: "{{ item }}"
    dest: "/etc/{{ item }}" 
    mode: 0644
  with_items:
    - dnsmasq.conf
  notify:
    - restart dnsmasq

- name: copy hosts
  copy: 
    src: "{{ item }}"
    dest: "/etc/hosts" 
    mode: 0644
  with_items:
    - "{{ file_prefix }}_hosts"
  notify:
    - restart dnsmasq

- name: permit traffic in default zone for dns service
  ansible.posix.firewalld:
    service: dns
    permanent: yes
    state: enabled
  notify:
    - restart firewalld
  tags: first_run

