---
# file: cluster.yml

- hosts: ceph_mgrs
  remote_user: root
  gather_facts: false
  roles:
    - common
    - ceph-adm

- hosts: ceph_mons
  remote_user: root
  gather_facts: false
  roles:
    - common
    - ceph-host

- hosts: ceph_osds
  remote_user: root
  gather_facts: false
  roles:
   - common
   - ceph-host
   - mlnx_ofed
   - mlnx_mft
