---
# file: cluster.yml
- hosts: dns
  remote_user: root
  gather_facts: true
  roles:
    - common
    - network
    - dns
    
- hosts: nginx
  remote_user: root
  gather_facts: true
  roles:
    - common
    - nginx

- hosts: k3s_cmd
  remote_user: root
  gather_facts: true
  roles:
    - common
    - k3s-linux
    - k3s-config

- hosts: k3s_workload
  remote_user: root
  gather_facts: true
  roles:
    - common
    - k3s-linux

- hosts: samba
  remote_user: root
  gather_facts: true
  roles:
    - common
    - ceph-client
    - samba-vfsceph

- hosts: ceph_mgrs
  remote_user: root
  gather_facts: true
  roles:
    - common
#    - network
    - ceph-adm
    - ceph-host

- hosts: ceph_mons
  remote_user: root
  gather_facts: true
  roles:
    - common
#    - network
    - ceph-host

- hosts: ceph_osds
  remote_user: root
  gather_facts: true
  roles:
    - common
#    - network
    - ceph-host
#   - mlnx_ofed
#   - mlnx_mft

- hosts: ceph_vm_osds
  remote_user: root
  gather_facts: true
  roles:
    - common
    - ceph-host

- hosts: ceph_vm_hosts
  remote_user: root
  gather_facts: true
  roles:
    - common
    - ceph-host

#- hosts: cluster
#  remote_user: root
#  gather_facts: true
#  roles:
#    - cluster
