---
# file: cluster.yml
- hosts: dns
  remote_user: root
  gather_facts: true
  roles:
    - common
    - network
    - dns

- hosts: ceph_mgrs
  remote_user: root
  gather_facts: true
  roles:
    - common
    - network
    - ceph-adm

- hosts: ceph_mons
  remote_user: root
  gather_facts: true
  roles:
    - common
    - network
    - ceph-host

- hosts: ceph_osds
  remote_user: root
  gather_facts: true
  roles:
    - common
    - network
    - ceph-host
#   - mlnx_ofed
#   - mlnx_mft

#- hosts: cluster
#  remote_user: root
#  gather_facts: true
#  roles:
#    - cluster

- hosts: samba
  remote_user: root
  gather_facts: true
  roles:
    - common
    - ceph-client
    - samba-vfsceph
