---
# file: roles/ceph-client/tasks/main.yml

- name: check for pre-requisites
  package:
    name:
      - systemd
      - podman
      - chrony
      - lvm2
      - python3
    state: present
  become: yes
  
- name: fetch cephadm script
  get_url:
    url: https://raw.githubusercontent.com/ceph/ceph/octopus/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0770'
  notify:
    - create ceph directory
    - add ceph repo

- name: install ceph-fuse package
  package:
    name: ceph-fuse
    state: present
