---
# file: roles/ceph-client/tasks/main.yml

- name: check for pre-requisites
  package:
    name:
      - systemd
      - podman
      - chrony
      - lvm2
      - python3
    state: present
  become: yes
  tags: first_run
  
- name: fetch ceph
  get_url:
    url: https://raw.githubusercontent.com/ceph/ceph/octopus/src/cephadm/cephadm
    dest: /root/cephadm
    mode: '0770'
  notify:
    - create ceph directory
    - add ceph repo
    - install ceph-fuse package
  tags: first_run

- name: make ceph conf from the mgr
  shell: "ceph config generate-minimal-conf | tee /root/ceph.conf"
  delegate_to: "{{ hostvars['host-mgr0'].ansible_host }}"
  run_once: true
  register: ceph_conf
  ignore_errors: true

- name: fetch ceph minimal config
  fetch: 
    src: "/root/ceph.conf"
    dest: "/tmp/fetched/"
    flat: "yes"
  delegate_to: "{{ hostvars['host-mgr0'].ansible_host }}"
  run_once: true
  ignore_errors: true
  register: fetch_config

- name: copy ceph minimal config
  copy: 
    src: "/tmp/fetched/ceph.conf"
    dest: "/etc/ceph/ceph.conf"
    mode: 0644
  ignore_errors: true

- name: create cephx user and get key
  shell: "ceph fs authorize village_general client.{{ inventory_hostname }} / rw | tee /root/ceph.client.{{ inventory_hostname }}.keyring"
  delegate_to: "{{ hostvars['host-mgr0'].ansible_host }}"
  run_once: true
  ignore_errors: true

- name: fetch ceph keyring
  fetch: 
    src: "/root/ceph.client.{{ inventory_hostname }}.keyring"
    dest: "/tmp/fetched/"
    flat: "yes"
  delegate_to: "{{ hostvars['host-mgr0'].ansible_host }}"
  run_once: true
  ignore_errors: true
  register: fetch_config

- name: copy ceph keyring
  copy: 
    src: "/tmp/fetched/ceph.client.{{ inventory_hostname }}.keyring"
    dest: "/etc/ceph/ceph.client.{{ inventory_hostname }}.keyring"
    mode: 0600
  ignore_errors: true

- name: enable ceph-fuse.target
  service:
    name: ceph-fuse.target
    state: started
    enabled: yes
